package org.opentcs.guing.application.action.report.form;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import com.aubot.hibernate.database.DatabaseSessionFactory;
import org.opentcs.guing.application.action.report.statistics.ErrorStatisticPanel;
import org.opentcs.guing.application.action.report.statistics.UIPluggablePanel;
import org.opentcs.guing.application.action.report.statistics.VehicleRouteHistoryStatisticsPanel;
import org.opentcs.guing.util.I18nPlantOverview;
import org.opentcs.guing.util.ResourceBundleUtil;
import org.opentcs.guing.util.UserMessageHelper;
import org.opentcs.hibernate.HibernateConfiguration;

import javax.inject.Inject;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author nguye
 */
public class VehicleStatistics
    extends javax.swing.JFrame{

  private final ResourceBundleUtil bundle = ResourceBundleUtil.getBundle(I18nPlantOverview.STATISTICS_PATH);

  private final HibernateConfiguration configuration;

  JRadioButton rdoErrorStatistic = new JRadioButton(bundle.getString("statisticPanel.radiobtnStatistic"));

  JRadioButton rdoVehicleRouteHistoryStatistic = new JRadioButton(bundle.getString("statisticPanel.radiobtnVehicleRouteHistoryStatistic"));

  ButtonGroup grpReportType = new ButtonGroup();

  UIPluggablePanel pnStat;

  UIPluggablePanel pnVRHStat;

  private final UserMessageHelper messageHelper;

  private final DatabaseSessionFactory sessionFactory;

  /**
   * Creates new form VehicleStatistics
   */
  @Inject
  public VehicleStatistics(HibernateConfiguration configuration,
                           UserMessageHelper messageHelper,
                           DatabaseSessionFactory sessionFactory) {
    this.configuration = configuration;
    this.messageHelper = messageHelper;
    this.sessionFactory = sessionFactory;
    initComponents();
    initComponentsExtra();
    enableUI(sessionFactory.isInitialized());
    if (!sessionFactory.isInitialized()) {
      messageHelper.showMessageDialog(bundle.getString("statisticPanel.error.connectionFailed.title"),
                                      bundle.getString("statisticPanel.error.connectionFailed.message"),
                                      UserMessageHelper.Type.ERROR);
    }
  }

  private void initComponentsExtra() {
    setLocationRelativeTo(null);
    pnStat = new ErrorStatisticPanel(configuration, sessionFactory);
    pnVRHStat = new VehicleRouteHistoryStatisticsPanel(configuration, sessionFactory);
    setTitle(bundle.getString("statisticPanel.title"));
    pnReport.add(pnStat, rdoErrorStatistic.getText());
    pnReport.add(pnVRHStat, rdoVehicleRouteHistoryStatistic.getText());
    grpReportType.add(rdoErrorStatistic);
    grpReportType.add(rdoVehicleRouteHistoryStatistic);
    pnReportType.add(rdoErrorStatistic);
    pnReportType.add(rdoVehicleRouteHistoryStatistic);
    rdoErrorStatistic.setSelected(true);
    rdoErrorStatistic.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    rdoErrorStatistic.addActionListener(e -> {
      ((CardLayout) pnReport.getLayout()).show(pnReport, rdoErrorStatistic.getText());

    });
    rdoVehicleRouteHistoryStatistic.addActionListener(e -> ((CardLayout) pnReport.getLayout()).show(pnReport, rdoVehicleRouteHistoryStatistic.getText()));
  }

  private void enableUI(boolean enable) {
    pnStat.enableUI(enable);
    pnVRHStat.enableUI(enable);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnReportType = new javax.swing.JPanel();
    pnReport = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setPreferredSize(new java.awt.Dimension(800, 600));
    setSize(new java.awt.Dimension(800, 600));
    getContentPane().add(pnReportType, java.awt.BorderLayout.PAGE_START);

    pnReport.setLayout(new java.awt.CardLayout());
    getContentPane().add(pnReport, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel pnReport;
  private javax.swing.JPanel pnReportType;
  // End of variables declaration//GEN-END:variables
}
